add_files -norecurse -fileset [current_fileset] [list \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/AN2D4PO4.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/CKLNQD12PO4.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/HLS_cdp_icvt.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/HLS_cdp_ocvt.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/MUX2D4.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/MUX2HDD2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/NV_BLKBOX_BUFFER.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/NV_BLKBOX_SINK.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/NV_BLKBOX_SRC0.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/NV_BLKBOX_SRC0_X.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/NV_CLK_gate_power.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cacc/NV_NVDLA_CACC_CALC_int8.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cacc/NV_NVDLA_CACC_assembly_buffer.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cacc/NV_NVDLA_CACC_assembly_ctrl.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cacc/NV_NVDLA_CACC_calculator.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cacc/NV_NVDLA_CACC_delivery_buffer.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cacc/NV_NVDLA_CACC_delivery_ctrl.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cacc/NV_NVDLA_CACC_dual_reg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/include/simulate_x_tick.vh \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cacc/NV_NVDLA_CACC_regfile.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cacc/NV_NVDLA_CACC_single_reg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cacc/NV_NVDLA_CACC_slcg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_CVT_cell.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_DC_fifo.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_ctrl.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_fifo.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_pack.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_sg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_sg2pack_fifo.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_WT_fifo.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_cvt.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_dc.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_dma_mux.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_dual_reg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_img.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_regfile.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_shared_buffer.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_single_reg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_slcg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_status.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_wt.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_INTP_unit.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_LUT_CTRL_unit.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_LUT_ctrl.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_MUL_unit.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_bufferin_tp1.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_cvtin.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_cvtout.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_intp.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_lut.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_mul.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_nan.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_sum.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_syncfifo.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_REG_dual.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_REG_single.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_cq.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_eg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_ig.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_reg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_REG_dual.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_REG_single.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_dp.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_rdma.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_reg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_slcg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_wdma.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cfgrom/NV_NVDLA_CFGROM_rom.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_active.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_cfg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_mac.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_rt_in.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_rt_out.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_slcg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cmac/NV_NVDLA_CMAC_REG_dual.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cmac/NV_NVDLA_CMAC_REG_single.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cmac/NV_NVDLA_CMAC_core.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cmac/NV_NVDLA_CMAC_reg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/csb_master/NV_NVDLA_CSB_MASTER_csb2falcon_fifo.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/csb_master/NV_NVDLA_CSB_MASTER_falcon2csb_fifo.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/csc/NV_NVDLA_CSC_SG_dat_fifo.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/csc/NV_NVDLA_CSC_SG_wt_fifo.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/csc/NV_NVDLA_CSC_WL_dec.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/csc/NV_NVDLA_CSC_dl.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/csc/NV_NVDLA_CSC_dual_reg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/csc/NV_NVDLA_CSC_regfile.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/csc/NV_NVDLA_CSC_sg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/csc/NV_NVDLA_CSC_single_reg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/csc/NV_NVDLA_CSC_slcg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/csc/NV_NVDLA_CSC_wl.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_DMAIF_rdreq.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_DMAIF_rdrsp.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_DMAIF_wr.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/glb/NV_NVDLA_GLB_CSB_reg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/glb/NV_NVDLA_GLB_csb.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/glb/NV_NVDLA_GLB_ic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/NV_NVDLA_HLS_saturate.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/NV_NVDLA_HLS_shiftleftsu.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/NV_NVDLA_HLS_shiftrightsatsu.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/NV_NVDLA_HLS_shiftrightsu.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_MCIF_CSB_reg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_MCIF_csb.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_IG_arb.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_IG_bpt.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_IG_cvt.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_IG_spt.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_cq.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_eg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_ig.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_IG_arb.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_IG_bpt.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_IG_cvt.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_IG_spt.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_cq.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_eg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_ig.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_read.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_write.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_dram.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_CORE_cal1d.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_CORE_cal2d.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_CORE_preproc.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_CORE_unit1d.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_REG_dual.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_REG_single.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_cq.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_eg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_ig.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_reg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_REG_dual.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_REG_single.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_WDMA_cmd.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_WDMA_dat.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_core.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_nan.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_rdma.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_reg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_slcg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_PDP_wdma.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_BRDMA_cq.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_BRDMA_gate.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_BRDMA_lat_fifo.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_gate.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_pack.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_unpack.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_C_int.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_X_int_alu.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_X_int_mul.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_X_int_relu.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_X_int_trt.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_c.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_prelu.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_relu.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_sync2data.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_x1_int.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_x2_int.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_EG_cmd.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_EG_din.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_EG_dout.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_cq.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_eg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_gate.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_ig.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_NRDMA_cq.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_NRDMA_gate.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_NRDMA_lat_fifo.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_EG_ro.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_REG_dual.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_REG_single.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_dmaif.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_eg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_ig.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_pack.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_reg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_unpack.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_REG_dual.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_REG_single.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_DAT_in.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_DAT_out.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_cmd.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_dat.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_gate.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_intr.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_brdma.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_cmux.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_core.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_mrdma.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_nrdma.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_rdma.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_reg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_wdma.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_XXIF_libs.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/apb2csb/NV_NVDLA_apb2csb.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cacc/NV_NVDLA_cacc.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cbuf/NV_NVDLA_cbuf.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_cdma.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_cdp.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cfgrom/NV_NVDLA_cfgrom.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cmac/NV_NVDLA_cmac.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/car/NV_NVDLA_core_reset.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/csb_master/NV_NVDLA_csb_master.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/csc/NV_NVDLA_csc.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/glb/NV_NVDLA_glb.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/include/NV_HWACC_NVDLA_tick_defines.vh \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/top/NV_NVDLA_partition_a.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/top/NV_NVDLA_partition_c.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/top/NV_NVDLA_partition_m.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/top/NV_NVDLA_partition_o.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/top/NV_NVDLA_partition_p.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/NV_NVDLA_pdp.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/car/NV_NVDLA_reset.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_sdp.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/car/NV_NVDLA_sync3d.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/car/NV_NVDLA_sync3d_c.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/car/NV_NVDLA_sync3d_s.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/top/NV_nvdla.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/OR2D1.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMDP_128X11_GL_M2_E2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMDP_128X6_GL_M2_E2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMDP_16X256_GL_M1_E2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMDP_16X272_GL_M1_E2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMDP_16X64_GL_M1_E2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMDP_256X4_GL_M2_E2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMDP_256X7_GL_M2_E2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMDP_256X8_GL_M2_E2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMDP_60X22_GL_M1_E2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMDP_80X14_GL_M2_E2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMDP_80X15_GL_M2_E2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMDP_80X9_GL_M2_E2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMDP_8X66_GL_M1_E2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_128X18_GL_M2_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_160X16_GL_M2_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_160X65_GL_M2_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_256X64_GL_M2_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_64X66_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_80X66_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/SDFCNQD1.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/SDFQD1.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/SDFSNQD1.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/ScanShareSel_JTAG_reg_ext_cg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/int_sum_block_tp1.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_128x18.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_128x18_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_16x256.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_16x256_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_16x272.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_16x272_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_16x64.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_16x64_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_256x3.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_256x3_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_256x64.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_256x64_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_256x7.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_256x7_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_128x11.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_128x11_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_128x6.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_128x6_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_160x16.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_160x16_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_160x65.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_160x65_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_61x65.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_61x65_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_80x14.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_80x14_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_80x65.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_80x65_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_8x65.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_8x65_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwst_256x8.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwst_256x8_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsthp_19x4.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsthp_60x21.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsthp_60x21_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsthp_80x15.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsthp_80x15_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsthp_80x9.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsthp_80x9_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/nvdla_small.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/oneHotClk_async_read_clock.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/oneHotClk_async_write_clock.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/p_SDFCNQD1PO4.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/p_SSYNC2DO_C_PP.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/p_SSYNC3DO.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/p_SSYNC3DO_C_PPP.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/p_SSYNC3DO_S_PPP.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/p_STRICTSYNC3DOTM_C_PPP.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/sync2d_c_pp.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/sync3d.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/sync3d_c_ppp.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/sync3d_s_ppp.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/sync_reset.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/CKLNQD12.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/HLS_fp32_sub.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMDP_64X10_GL_M2_E2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/retiming/NV_NVDLA_RT_cmac_b2cacc.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/HLS_fp32_to_fp17.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_wg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_32x256_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsthp_80x72.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_128X64_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_128x64.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_WT_wgs_fifo.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/nocif/NV_NVDLA_nocif.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_128X256_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_rf_ctrl.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/cal1d_fp16_pool_sum.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/NV_DW02_tree.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsp_61x514.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_fifo.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_256X144_GL_M2_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_seq_gen.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_61x514.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_512X72_GL_M4_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/NV_NVDLA_CDP_HLS_icvt.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/fp_format_cvt.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_128x256_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsthp_80x9.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_248X144_GL_M2_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsp_80x65.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_32X224_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/assertion_header.vh \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/retiming/NV_NVDLA_RT_csb2cacc.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_lut_expn.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsp_128x6.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_int_core.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_80X72_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_32x272.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/retiming/NV_NVDLA_RT_csc2cmac_a.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_32x512_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/bdma/NV_NVDLA_BDMA_load.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_256x512_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_int_inp.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_80X226_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_ERDMA_cq.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMDP_32X32_GL_M1_E2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/HLS_fp17_sub.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/bdma/NV_NVDLA_BDMA_cq.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_245x514.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_512x64.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_16x256.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_idx_top.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_80X256_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/car/NV_NVDLA_ssync3d_c.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_64X64_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/retiming/NV_NVDLA_RT_csc2cmac_b.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_512x512.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/bdma/NV_NVDLA_BDMA_store.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_64x1024.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_64x10.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_20x289.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/HLS_fp17_add.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/HLS_fp16_to_fp32.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/glb/NV_NVDLA_GLB_fc.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_32X256_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_64x1024_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_64X160_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwst_256x8.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_64X288_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_80x514.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_dr2drc.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/car/NV_NVDLA_ssync3d.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_Y_lut.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_256x11.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_32x512.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsthp_60x168.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_512x512_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_lut_line.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_erdma.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_64x10_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_80x514_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_160x514_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/PGAOPV_DFCNQD2PO4.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_61x64.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsp_256x11.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_512X64_GL_M4_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/retiming/NV_NVDLA_RT_sdp2nocif.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_256x11_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_ERDMA_gate.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_64x1088.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/PGAOPV_INVD2PO4.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_512x256_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_80x256_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_32X288_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsp_20x289.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_512x512.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_dual_reg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsthp_60x21.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_32x544.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsp_245x514.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_64x18.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_245x514_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsthp_19x80_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_20x289_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_32x16.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_64x1088_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_32x32_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_32x16_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_wrdma_data.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsthp_19x80.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_256x64.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_80x16.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/retiming/NV_NVDLA_RT_cacc2glb.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/HLS_fp17_to_fp16.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/HLS_fp32_mul.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_64x116.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_ERDMA_lat_fifo.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsp_61x65.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/bdma/NV_NVDLA_BDMA_csb.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/PGAOPV_AN2D2PO4.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/NV_NVDLA_CDP_HLS_ocvt.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMDP_20X288_GL_M1_E2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_single_reg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/HLS_fp17_to_fp32.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_64x116.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/pdp/fp16_4add.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/int_sum_block.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_rf_rcmd.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_64x1088.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_128x256.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_32x32.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsp_160x514.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsthp_80x15.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_rf_wcmd.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_32x272_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/retiming/NV_NVDLA_RT_csb2cmac.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsp_80x16.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsp_8x65.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_16x64.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_int_idx.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_60X168_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_slcg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_32x768.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/bdma/NV_NVDLA_BDMA_gate.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsthp_19x80.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_128x256.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_16x272.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_WG_fifo.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_256x3.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_256x512.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/csc/NV_NVDLA_CSC_pra_cell.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsp_80x514.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsp_160x65.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_32x768_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/NV_NVDLA_HLS_shiftrightss.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMDP_20X80_GL_M1_E2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/fp_sum_block.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsp_61x64.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_512x256.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_512x64_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_y.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_int_alu.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_80X16_GL_M2_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_cvt_top.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsp_80x14.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_wrdma_cmd.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/HLS_fp32_add.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_32x16.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_128x64.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_bufferin.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsthp_60x168.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_WT_sp_arb.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_wr_req.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsp_80x256.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_64x18.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/retiming/NV_NVDLA_RT_cmac_a2cacc.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/HLS_fp16_to_fp17.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/NV_DW_lsd.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_32x768.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/bdma/NV_NVDLA_bdma.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsthp_80x72.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_64x116_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/assertion_task.vh \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsp_160x16.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_256X11_GL_M4_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_128x18.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/NV_NVDLA_HLS_shiftrightusz.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_512X40_GL_M4_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsthp_19x32.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_128x64_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_160X144_GL_M2_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/bdma/NV_NVDLA_BDMA_reg.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_61x514_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_32x544_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_160x514.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_512X8_GL_M4_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_dma.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_32X272_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_32x544.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_64x18_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsthp_19x4.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_64X226_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_32x256.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsp_32x32.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_61x64_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsthp_60x168_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMDP_32X16_GL_M1_E2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMDP_64X18_GL_M2_E2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_rf_core.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/HLS_uint16_to_fp17.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/NV_DW_minmax.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_64X224_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_512x256.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_64x10.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_256x7.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/HLS_fp17_mul.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_160X82_GL_M2_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_80X288_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsthp_19x32.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rws_256x512.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_inp_top.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_64x1024.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_512x64.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rws_32x512.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_256X80_GL_M2_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/HLS_fp32_to_fp16.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_int_mul.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/rubik/NV_NVDLA_rubik.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsthp_80x72_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_regfile.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_32X192_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_int_cvt.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_80x16_logic.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/synth/nv_ram_rwsp_80x256.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_intr.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/fpga/small_rams/nv_ram_rwsp_128x11.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_248X82_GL_M2_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_unpack.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/nvdla/cdma/NV_NVDLA_CDMA_WT_wrr_arb.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/rams/model/RAMPDP_64X116_GL_M1_D2.v \
    $ROOT/../nvdla/block-nvdla-sifive/vsrc/small/vmod/vlibs/LNQD1PO4.v \
]
