set_property SRC_FILE_INFO {cfile:C:/Users/2640084/Desktop/ubuntu/shared/projects/cheshire-env-nvdla-g2/vivado_zcu106_uart/vivado_zcu106_uart.srcs/constrs_1/new/zcu106.xdc rfile:../../../vivado_zcu106_uart.srcs/constrs_1/new/zcu106.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH17 [get_ports program_tx1_o]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL17 [get_ports uart_coming]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN8 [get_ports uart_rx_i]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP9 [get_ports program_tx2_o]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL11 [get_ports led_tx_o]
